name: Chance color snk github
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "--cs:purple"
          replace: "--cs:red"
          include: "**github-contribution-grid-snake.svg"
          regex: true
